apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice-bg
  labels:
    app: paymentservice-bg
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  replicas: 3
  selector:
    matchLabels:
      app: paymentservice-bg
  template:
    metadata:
      labels:
        app: paymentservice-bg
    spec:
      containers:
        - name: server
          image: ormgair/hipster_shop_paymentservice:0.2
          ports:
            - containerPort: 50051
          env:
            - name: PORT
              value: "50051"
            - name: DISABLE_PROFILER
              value: "1"
