apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: frontend
  name: frontend
spec:
  containers:
    - env:
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: NONE
        - name: CURRENCY_SERVICE_ADDR
          value: NONE
        - name: CART_SERVICE_ADDR
          value: NONE
        - name: RECOMMENDATION_SERVICE_ADDR
          value: NONE
        - name: CHECKOUT_SERVICE_ADDR
          value: NONE
        - name: SHIPPING_SERVICE_ADDR
          value: NONE
        - name: AD_SERVICE_ADDR
          value: NONE
      image: ormgair/hipster_shop_frontend:0.1
      name: frontend
      resources: { }
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: { }
