apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    app: web
spec:
  containers:
    - name: web
      image: ormgair/nginx_exposed:0.1
      volumeMounts:
        - name: app
          mountPath: /app
  volumes:
    - name: app
      emptyDir: { }
  initContainers:
    - name: init-web
      image: busybox:1.36
      command: [ 'sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh' ]
      volumeMounts:
        - name: app
          mountPath: /app